# Generated by Django 2.2 on 2019-05-02 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0003_photo_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='save_post',
            field=models.ManyToManyField(related_name='save_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
