# Generated by Django 2.2 on 2019-05-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photo_save_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='save_post',
            new_name='save',
        ),
    ]
