# Generated by Django 2.2 on 2019-05-03 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20190502_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='save_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
