# Generated by Django 2.2 on 2019-05-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20190503_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='save',
            new_name='favorite',
        ),
    ]
