# Generated by Django 2.2 on 2019-05-07 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0007_auto_20190503_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='mylist',
            field=models.ManyToManyField(blank=True, related_name='mylist', to=settings.AUTH_USER_MODEL),
        ),
    ]
