# Generated by Django 2.2 on 2019-05-08 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_photo_mylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='mylist',
        ),
    ]
